# Target file name.
TARGET = libethernet

# List C source files here.
CCSOURCES = stm32f4x7_eth.c eth_bsp.c

# List Assembler to be assembled with NASM here
ASOURCES = 

# Additional include paths to consider
INCLUDES =	$(ROOT)/libs/$(TARGET)/inc $(ROOT)/libs/libstm32f4xx/inc $(ROOT)/libs/cmsis/inc


# Folder for object files
OBJDIR = obj

# Folder for sourcecode
SRCDIR = src

# Additional defines
DEFINES := 

-include $(ROOT)/build/libs.mak
