# Target file name.
TARGET = libfatfs

# List C source files here.
CCSOURCES = ff.c

# List Assembler to be assembled with NASM here
ASOURCES = 

# Additional include paths to consider
INCLUDES =	$(ROOT)/libs/$(TARGET)/inc

# Folder for object files
OBJDIR = obj

# Folder for sourcecode
SRCDIR = src

# Additional defines
DEFINES := -DARM_MATH_CM4

-include $(ROOT)/build/libs.mak
