# Target file name.
TARGET = libusbdevice

# List C source files here.
CCSOURCES = usbd_core.c usbd_ioreq.c usbd_req.c

# List Assembler to be assembled with NASM here
ASOURCES = 

# Additional include paths to consider
INCLUDES =	$(ROOT)/libs/$(TARGET)/inc \
			$(ROOT)/libs/libstm32f4xx/inc \
			$(ROOT)/libs/cmsis/inc \
			$(ROOT)/libs/libusbcore/inc

# Folder for object files
OBJDIR = obj

# Folder for sourcecode
SRCDIR = src

# Additional defines
DEFINES := 

-include $(ROOT)/build/libs.mak
